### ISSUE TITLE
BulkInsert throws on multiline VALUES.

### ISSUE THREAD

**Issue by EthanRutherford** [Faithlife/DapperUtility#3]
Due to the structure of the regex [here](https://github.com/Faithlife/DapperUtility/blob/master/src/Faithlife.Utility.Dapper/BulkInsertUtility.cs#L260-L261), splitting values into multiple lines, which is often desired when inserting into tables with several columns, BulkInsert will throw an Argument exception with error message `sql does not contain "VALUES"`.

This ought to be supported, as the sql is perfectly valid, and the error message is unhelpful, since the issue is that the VALUES are not all on one line, not that they are missing.

**Comment by EthanRutherford** [comment]
Additionally, inexplicably, the regex asserts that the values statement is followed with an ellipsis (`\.\.\.`), which I'm fairly certain is not valid sql.

**Comment by bgrainger** [comment]
What is the exact SQL you're using?

I inserted newlines everywhere I possibly could and `s_valuesClauseRegex.Matches.Count` was still 1.

```csharp
s_valuesClauseRegex.Matches("VALUES\r\n(\r\n@a,\r\n@b\r\n)\r\n...").Count // == 1
```

**Comment by bgrainger** [comment]
Note the requirement to include `...` after the `VALUES` clause, as explained in [the documentation](https://faithlife.github.io/DapperUtility/BulkInsert.html#solution).

**Comment by EthanRutherford** [comment]
Ah, I had initially been missing the `...` in my sql, and had seen `RegexOptions.Singleline` and assumed that was the issue.
